FROM node:21-alpine3.18

RUN mkdir -p /app/
WORKDIR /app
COPY packages/server/package.json /app/package.json
RUN yarn install

COPY packages/server/src/ ./src
COPY packages/server/prisma/schema.prisma ./prisma/schema.prisma
COPY packages/server/.env ./.env
RUN yarn db:migrate
RUN yarn db:push

EXPOSE 8000
CMD [ "yarn", "start" ]