services:
  backend:
    image: note-backend
    container_name: note-backend-compose
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: note-frontend
    container_name: note-frontend-compose
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
