FROM node:20-alpine AS build-stage
WORKDIR /app
WORKDIR /app/packages/client
COPY packages/client/package.json ./package.json
COPY yarn.lock ./yarn.lock
RUN yarn install --frozen-lockfile
COPY packages/client/ ./
RUN sed -i 's/"build": "tsc && vite build"/"build": "vite build"/' package.json
RUN yarn build
FROM nginx:stable-alpine AS release-stage
COPY --from=build-stage /app/packages/client/dist/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 3000